name: Auto Check-in Bot

on:
  workflow_dispatch: # chạy tay
  schedule:
    # 00:15 VN = 17:15 UTC (ngày hôm trước)
    - cron: "15 17 * * *"
    # 23:30 VN = 16:30 UTC
    - cron: "30 16 * * *"
  push:
    branches: [ "main" ] # đánh thức repo

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install chromium

      - name: Run bot
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: node bot.js

      # upload screenshot nếu có lỗi
      - name: Upload error screenshot
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: error-image
          path: error.png
          if-no-files-found: ignore

      # upload tất cả ảnh screenshot
      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: "*.png"
          if-no-files-found: ignore
