name: Keep Alive Bot

on:
  schedule:
    - cron: "*/5 * * * *"   # chạy mỗi 5 phút
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Wake up repo
        run: echo "repo is alive"
