name: Test Cron

on:
  schedule:
    - cron: "*/5 * * * *" # mỗi 5 phút
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print time
        run: echo "Cron working at $(date)"
