name: Test Cron Auto

on:
  schedule:
    - cron: "*/5 * * * *"   # chạy mỗi 5 phút (an toàn để test)

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Show time
        run: echo "Cron is running at $(date)"
