name: Test Cron Only

on:
  schedule:
    - cron: "*/2 * * * *"   # chạy mỗi 2 phút (dễ test)

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Show time
        run: echo "Cron is running at $(date)"
